<#
.SYNOPSIS
    Packages magisk-picoet-enhance into a Magisk zip (runtime injection; zero PICO bytes).

.DESCRIPTION
    Offline only. Stages the module scripts (LF line endings) plus our two built artifacts
    (bin/picoet-inject, lib/libpicoet_hook.so), generates hashes.sh, and scans the staged tree:
    every ELF file must be one of our artifacts and no file may match any known PICO library
    SHA256. Writes artifacts/magisk-picoet-enhance-v<version>.zip. It does not touch any device.
    The PICO libraries are never copied or patched: the payload references them by name and
    numeric offset at runtime, behind version guards.

.EXAMPLE
    pwsh -File build-picoet-enhance.ps1
#>
[CmdletBinding()]
param(
    [string]$HookDir = '',
    [string]$OutputDir = ''
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$moduleDir = Join-Path $PSScriptRoot 'magisk-picoet-enhance'
if (-not $HookDir) { $HookDir = Join-Path $PSScriptRoot 'hook' }
if (-not $OutputDir) { $OutputDir = Join-Path $root 'artifacts' }

$scripts = @('module.prop', 'customize.sh', 'post-fs-data.sh', 'service.sh', 'picoet.sh',
             'action.sh', 'uninstall.sh', 'sepolicy.rule', 'README.md')
foreach ($name in $scripts) {
    $p = Join-Path $moduleDir $name
    if (-not (Test-Path -LiteralPath $p)) { throw "Missing required module file: $p" }
}

$injector = Join-Path $HookDir 'build\picoet-inject'
$payload = Join-Path $HookDir 'build\libpicoet_hook.so'
foreach ($t in @($injector, $payload)) {
    if (-not (Test-Path -LiteralPath $t)) { throw "Missing build artifact: $t (run hook/build-hook.ps1 first)" }
}
$injectSha = (Get-FileHash -LiteralPath $injector -Algorithm SHA256).Hash.ToLower()
$payloadSha = (Get-FileHash -LiteralPath $payload -Algorithm SHA256).Hash.ToLower()

# Known PICO library builds (offline payloads and stock). None of these may appear in the zip,
# and the ELF allowlist below makes any other PICO binary or derivative fail the build too.
$picoShas = @(
    '0ce64527abb923b4eb8bb98f9df8b1c3e73ad95a460460f4140157c0a7363ba1', # plugin stock
    'ebe4071c939406c8409e51df7f332e74840a5b3ebf86776c731be23e8e927210', # plugin left
    '9bc905b9aa060508ac4d5f4d01ccc7410f31b498641b1e722e48c0da9852f624', # plugin right
    '166c1e9e97f0998005f2c1a07022ed3a13871b214ccd63440c94c7c7226669c2', # plugin dual
    '7d39b99ee36ab13a5f39fefa2cfe6677ccc419b65d07e710831a569678f94a5c', # service stock
    '0cde55edec2e7fd3aed7d44cfdf46708c09d47b2e8b48b1e0f8fb08f7f31e031'  # service gate
)

$stage = Join-Path ([IO.Path]::GetTempPath()) "picoet-enhance-$([guid]::NewGuid().ToString('N'))"
New-Item -ItemType Directory -Force -Path (Join-Path $stage 'bin'), (Join-Path $stage 'lib') | Out-Null
try {
    foreach ($name in $scripts) {
        $text = [IO.File]::ReadAllText((Join-Path $moduleDir $name)) -replace "`r`n", "`n"
        [IO.File]::WriteAllText((Join-Path $stage $name), $text, [Text.UTF8Encoding]::new($false))
    }
    Copy-Item -LiteralPath $injector -Destination (Join-Path $stage 'bin\picoet-inject')
    Copy-Item -LiteralPath $payload -Destination (Join-Path $stage 'lib\libpicoet_hook.so')
    $hashText = "# generated by build-picoet-enhance.ps1`nINJECT_SHA=$injectSha`nPAYLOAD_SHA=$payloadSha`n"
    [IO.File]::WriteAllText((Join-Path $stage 'hashes.sh'), $hashText, [Text.UTF8Encoding]::new($false))

    # --- zero-PICO scan: known-hash rejection + ELF allowlist + structure ---
    foreach ($f in (Get-ChildItem -Recurse -File $stage)) {
        $h = (Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash.ToLower()
        if ($picoShas -contains $h) { throw "staged file $($f.FullName) matches a known PICO library hash" }
        $bytes = [IO.File]::ReadAllBytes($f.FullName)
        if ($bytes.Length -ge 4 -and $bytes[0] -eq 0x7f -and $bytes[1] -eq 0x45 -and
            $bytes[2] -eq 0x4c -and $bytes[3] -eq 0x46) {
            if ($h -ne $injectSha -and $h -ne $payloadSha) {
                throw "staged ELF $($f.FullName) is neither our injector nor our payload"
            }
        }
    }
    if (Test-Path -LiteralPath (Join-Path $stage 'payload')) { throw 'stage contains a payload/ directory' }
    foreach ($s in (Get-ChildItem -Recurse -File $stage -Filter *.so)) {
        if ((Get-FileHash -LiteralPath $s.FullName -Algorithm SHA256).Hash.ToLower() -ne $payloadSha) {
            throw "unexpected .so in stage: $($s.FullName)"
        }
    }

    $props = Get-Content -Raw (Join-Path $moduleDir 'module.prop')
    $id = ([regex]::Match($props, '(?m)^id=(.+)$')).Groups[1].Value.Trim()
    $version = ([regex]::Match($props, '(?m)^version=(.+)$')).Groups[1].Value.Trim()
    if (-not $id) { throw 'module.prop has no id' }
    if (-not $version) { throw 'module.prop has no version' }
    New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
    $zipPath = Join-Path $OutputDir "magisk-$id-v$version.zip"
    if (Test-Path -LiteralPath $zipPath) { Remove-Item -LiteralPath $zipPath -Force }
    # Build the archive entry by entry so names use forward slashes (ZIP spec / Magisk
    # unzip); ZipFile.CreateFromDirectory would write Windows backslashes.
    Add-Type -AssemblyName System.IO.Compression
    $zipStream = [IO.File]::Open($zipPath, [IO.FileMode]::Create)
    $archive = New-Object System.IO.Compression.ZipArchive($zipStream, [System.IO.Compression.ZipArchiveMode]::Create)
    try {
        foreach ($f in (Get-ChildItem -Recurse -File $stage)) {
            $rel = $f.FullName.Substring($stage.Length + 1) -replace '\\', '/'
            $entry = $archive.CreateEntry($rel, [IO.Compression.CompressionLevel]::Optimal)
            $es = $entry.Open()
            $fs = [IO.File]::OpenRead($f.FullName)
            try { $fs.CopyTo($es) } finally { $fs.Dispose(); $es.Dispose() }
        }
    }
    finally {
        $archive.Dispose()
        $zipStream.Dispose()
    }
    Write-Host "built $zipPath ($((Get-Item -LiteralPath $zipPath).Length) bytes, id=$id version=$version)"
    Write-Host "  injector sha256 $injectSha"
    Write-Host "  payload  sha256 $payloadSha"
    Write-Host '  zero-PICO scan: OK (ELF allowlist + known PICO hashes absent)'
}
finally {
    Remove-Item -Recurse -Force $stage
}
